### PR TITLE
Fix Sort by Year Bug (#12101)

### LINKED ISSUE #12101: [Issue]: Sort by year bug
### Please describe your bug

When sorting movies by year, I noticed that not all movies are sorted.
This does not happen with tv series, at least not in my experience.

As you can see in the image below, when sorting by release year in ascending order, the first 11 movies are from later years. The same happens when sorting in descending order (the incorrect movies are at the end, instead of the beginning).
The metadata is correct, and no spaces are present.

### Reproduction Steps

1. Sort movies by year
2. Not all movies are sorted correctly

### Jellyfin Version

10.9.0

### if other:

_No response_

### Environment

```markdown
OS: Linux
Virtualization: Docker
Clients: Browser and Android
Browser: Firefox and Chrome
Jellyfin Version: 10.9.6
Playback: Direct Play
Reverse Proxy: none
Storage: local NAS
```

### Jellyfin logs

```shell
nothing relevant
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jjwarrenSEP**
**Changes**
Broke out sort order mapping into a static testable file.
Added default behavior for when sorting is used on a null Premier Date.
Added unit tests for the Sort Order case of Premier Date.

**Issues**
Fixes #12101

### CODE REVIEW

**Comment by jjwarrenSEP** [comment]
Not sure why the Merge Conflict Labeler failed but it doesn't seem to be due to a Merge Conflict. Do I need to recreate this PR or is something else going on?

**Comment by crobibero** [comment]
> Not sure why the Merge Conflict Labeler failed but it doesn't seem to be due to a Merge Conflict. Do I need to recreate this PR or is something else going on?

Looks like a github timeout, nothing to worry about on your end

**Review by Shadowghost — APPROVED** [review]

**Review by JPVenson — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

File: Jellyfin.Server.Implementations/Item/OrderMapper.cs [hunk 1]
```diff
@@ -0,0 +1,57 @@
+using System;
+using System.Linq;
+using System.Linq.Expressions;
+using Jellyfin.Data.Entities;
```
Comment (jhparker88) [inline Jellyfin.Server.Implementations/Item/OrderMapper.cs:4]: @crobibero After the merge, tests fail with "The type or namespace name 'Entities' does not exist in the namespace 'Jellyfin.Data'..."

```
Error: /home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Item/OrderMapper.cs(4,21): error CS0234: The type or namespace name 'Entities' does not exist in the namespace 'Jellyfin.Data' (are you missing an assembly reference?) [/home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj]
Error: /home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Item/OrderMapper.cs(22,35): error CS0246: The type or namespace name 'BaseItemEntity' could not be found (are you missing a using directive or an assembly reference?) [/home/runner/work/jellyfin/jellyfin/Jellyfin.Server.Implementations/Jellyfin.Server.Implementations.csproj]
  Jellyfin.Common.Tests -> /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.Common.Tests/bin/Release/net9.0/Jellyfin.Common.Tests.dll
Test run for /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.Common.Tests/bin/Release/net9.0/Jellyfin.Common.Tests.dll (.NETCoreApp,Version=v9.0)
  Jellyfin.MediaEncoding.Tests -> /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.MediaEncoding.Tests/bin/Release/net9.0/Jellyfin.MediaEncoding.Tests.dll
Test run for /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.MediaEncoding.Tests/bin/Release/net9.0/Jellyfin.MediaEncoding.Tests.dll (.NETCoreApp,Version=v9.0)
VSTest version 17.13.0 (x64)
```
