### ISSUE TITLE
After updating to 12.0, Server randomly closing, sometimes with ChunkLoadError

### ISSUE THREAD

**Issue by TheT113** [jellyfin/jellyfin#17916]
### Description of the bug

Jellyfin server is closing (in tray up, "Stop Jellyfin" becomes gray and "Start Jellyfin" becomes available) at random times. Sometimes if I am using it while it happens, I see an error code, like this:

```
ChunkLoadError

Loading CSS chunk 91068 failed. (error: http://localhost:8096/web/libraries.1b6e01d67fa7276dd291.css)

s.f.miniCss/e[a]</b.onload@http://localhost:8096/web/runtime.bundle.js?92243be6e1b950a9de11:1:46206
```

### Reproduction steps

Unclear. Happened in the middle of the night when I was not using Jellyfin. Had someone else who uses the server report to me it was down.

Update: I started editing some of my items in the metadata manager and it was closing the server *constantly*.

### What is the current _bug_ behavior?

Randomly stopping server.

### What is the expected _correct_ behavior?

Not that.

### Jellyfin Server version

12.0

### Specify the build version

12.0

### Environment

```markdown
- OS: Windows 10
```

### Jellyfin logs

```shell
Log doesn't show anything. Let me know if there's something I should provide that would show debug problems in logs.
```

### FFmpeg logs

```shell

```

**Comment by TheT113** [comment]
Got a different error just now:

```
Unexpected Application Error!
w.find is not a function

40726/fe/B<@http://localhost:8096/web/78701.d06a72f873e03eaaa404.chunk.js:1:7970
Bu@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:64687
14403/t.useMemo@http://localhost:8096/web/1133.bundle.js?92243be6e1b950a9de11:2:46448
fe@http://localhost:8096/web/78701.d06a72f873e03eaaa404.chunk.js:1:7917
hu@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:60311
zo@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:74349
xi@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:120119
bs@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:108506
vs@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:108434
gs@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:108295
as@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:105130
is@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:105512
Bl@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:46687
76067/rs/<@http://localhost:8096/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:103087
```

**Comment by theguymadmax** [comment]
Are you using the File Transformation plugin? Please list any third-party plugins you have installed.

**Comment by TheT113** [comment]
I uninstalled it before I posted any of this and am still getting the issue.

Edit: Nevermind, it refused to uninstall? Looking into it.

Edit2: Okay, was able to uninstall it. Did a test by editing a few metadata items and the server still shut down after a few.

The only other 3rd party plugin I have is Shoko.

<img width="1662" height="767" alt="Image" src="https://github.com/user-attachments/assets/33e40abc-9da8-45c7-b006-e350eb3e9a06" />

**Comment by TheT113** [comment]
Updated to the latest version of Shoko on the dev branch, 6.0.5.3112, issue is still occurring.

Edit: Disabled Shoko entirely, still occurring. Also, while doing this, noticed Anidb updated to 13.0.0.0, but still occurring.

**Comment by TheT113** [comment]
Just woke up to find it had shut off in the middle of the night, so that issue is still occurring. Would really appreciate some help here before I roll back.

**Comment by Shadowghost** [comment]
If you disable all plugins, does it still crash? If yes, anything in the server logs? Can you check your system log if Jellyfin was OOM killed?

**Comment by TheT113** [comment]
Many of the plugins don't have the option to disable them.

Okay. Now it isn't crashing. So I'll slowly start re-adding them and trying it to get down to the bottom of it...

Okay! Good news. I've narrowed it down. The issue appears to be "TMDb Box Sets", ver. 12.0.0.0.

The issue only occurs when editing movies, not TV shows. I'm going to guess it crashed overnight because it tried to run a box set scan. That said, if I go to scheduled tasks and choose "Scan library for new box sets", it fails (but doesn't shut down).

So! I shall disable the TMDb Box Sets plugin and wait for an update, I suppose?

**Comment by Shadowghost** [comment]
Yes, anything in the logs at all before it crashes?

**Comment by theguymadmax** [comment]
TMDb Box Sets: the old plugin will 100% crash your system. Run the update plugin task and restart the system afterwards.

**Comment by TheT113** [comment]
Oh, huh. I had run the update plugin task, but it didn't actually update it. I went into the plugin, saw a new version, and clicked install. Wonder why it didn't install automatically, like the other plugins.

Yep, looks like we are golden. Sorry for the inconvenience and thanks for the help!

**Comment by paladzin** [comment]
Got the same problem when using nginx proxy - fixed by enable:
Network->Use same published server URI for internal and external access

**Comment by Aulteran** [comment]
> Got the same problem when using nginx proxy - fixed by enable: Network->Use same published server URI for internal and external access

i turned this on and am still having the issue
