### PR TITLE
Allow tmdb as an alias for tmdbid provider id

### LINKED ISSUE #14928: Add support for other enclosing tags around filenames for tmdbid / imdbid
Trying to import / migrate my plex library into jellyfin, and had a fair number of mis-matches. I followed the general consensus and used series folders in the shape: `SeriesName {tmdbid-#####}`. Apparently JellyFin only supports brackets today.

I added support for both curly braces and parenthesis in the parser to make migration easier for anyone else that comes along.

#14927 addresses this, and the only functional change should be that `{}` and `()` are valid enclosers. I've kept all other restrictions in place.

### PR DESCRIPTION
**Pull request by theguymadmax**
**Changes**
Allow tmdb as an alias for tmdbid provider id

**Issues**
Combined with https://github.com/jellyfin/jellyfin/pull/14927
Fixes: #14928 , [feature request](https://features.jellyfin.org/posts/3727/support-for-plex-style-of-provider-id-in-names)

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

File: Emby.Server.Implementations/Library/PathExtensions.cs [hunk 1]
```diff
@@ -70,6 +70,12 @@ public static class PathExtensions
                 return match ? imdbId.ToString() : null;
             }
 
+            // Allow tmdb as an alias for tmdbid
+            if (attribute.Equals("tmdbid", StringComparison.OrdinalIgnoreCase))
+            {
+                return str.GetAttributeValue("tmdb");
```
Comment (IDisposable) [inline Emby.Server.Implementations/Library/PathExtensions.cs]: I realize there are no other machinations needed after this _currently_ but the `return` seems premature **IFF** there is no actual `"tmdb"` attribute. If someone later was to add other conditions before the final `return null;` they would never be hit which is a pit-of-despair waiting to happen. 

Should we only early-return **IFF** we have an actual `"tmdb"` attribute and just fall-through if not present?

**Comment by IDisposable** [comment]
Looks like there's a tweak needed in MusicBrainz

```text
Error: /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.Providers.Tests/ExternalId/MusicBrainzExternalUrlProviderTests.cs(44,21): error CS7036: There is no argument given that corresponds to the required parameter 'logger' of 'Plugin.Plugin(IApplicationPaths, IXmlSerializer, IApplicationHost, ILogger<Plugin>)' [/home/runner/work/jellyfin/jellyfin/tests/Jellyfin.Providers.Tests/Jellyfin.Providers.Tests.csproj]
  Jellyfin.MediaEncoding.Hls.Tests -> /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.MediaEncoding.Hls.Tests/bin/Release/net10.0/Jellyfin.MediaEncoding.Hls.Tests.dll
Test run for /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.MediaEncoding.Hls.Tests/bin/Release/net10.0/Jellyfin.MediaEncoding.Hls.Tests.dll (.NETCoreApp,Version=v10.0)
A total of 1 test files matched the specified pattern.
```

**Comment by theguymadmax** [comment]
> Looks like there's a tweak needed in MusicBrainz
> 
> ```
> Error: /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.Providers.Tests/ExternalId/MusicBrainzExternalUrlProviderTests.cs(44,21): error CS7036: There is no argument given that corresponds to the required parameter 'logger' of 'Plugin.Plugin(IApplicationPaths, IXmlSerializer, IApplicationHost, ILogger<Plugin>)' [/home/runner/work/jellyfin/jellyfin/tests/Jellyfin.Providers.Tests/Jellyfin.Providers.Tests.csproj]
>   Jellyfin.MediaEncoding.Hls.Tests -> /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.MediaEncoding.Hls.Tests/bin/Release/net10.0/Jellyfin.MediaEncoding.Hls.Tests.dll
> Test run for /home/runner/work/jellyfin/jellyfin/tests/Jellyfin.MediaEncoding.Hls.Tests/bin/Release/net10.0/Jellyfin.MediaEncoding.Hls.Tests.dll (.NETCoreApp,Version=v10.0)
> A total of 1 test files matched the specified pattern.
> ```

Yeah, unrelated to this PR.  Can you submit a fix? The tests aren't even syncing for me. It looks like we missed all those warnings on your PR.

**Comment by IDisposable** [comment]
> Yeah, unrelated to this PR. Can you submit a fix? The tests aren't even syncing for me. It looks like we missed all those warnings on your PR.

On it.  Was caused by https://github.com/jellyfin/jellyfin/pull/16780/changes#diff-0a3f4fca8bbb05a6d8bfe5efb3d67a588efe87ed2c449b8d07b95748e580ef45R34

**Comment by IDisposable** [comment]
Fix of the (unrelated) unit test in PR #16789 which when merged to master will unblock this compilation.

**Comment by IDisposable** [comment]
Test-fix PR merged, this should compile now. Not sure how to trigger that.

**Review by IDisposable — APPROVED** [review]
