### ISSUE TITLE
Dashboard fails to load with "r.map is not a function" error

### ISSUE THREAD

**Issue by wlygon7** [jellyfin/jellyfin#17989]
### Description of the bug

Attempting to open the admin Dashboard under a proxied domain (I tried under a Cloudflared Tunnel and Caddy) throws an unhandled client-side application error instead of rendering the page. The error occurs immediately on navigation, before any dashboard content is displayed.

### Reproduction steps

1. Run Jellyfin behind a reverse proxy (I tried it with both Cloudflare Tunnel and Caddy)
2. Access the web client through the proxied public hostname
3. Log in and navigate to Administration --> Dashboard
4. Observe the error
5. As a comparison, access the same server directly via its local IP:port

### What is the current _bug_ behavior?

Unexpected Application Error!
r.map is not a function

### What is the expected _correct_ behavior?

The Dashboard should load identically whether accessed via direct IP or through a reverse proxy.

### Jellyfin Server version

12.0

### Specify the build version

12.0

### Environment

```markdown
- OS: Ubuntu 24.04 LTS (Noble Numbat), LXC container
- Linux Kernel: 6.17.4-2-pve
- Virtualization: Proxmox LXC
- Clients: Web (browser)
- Browser: Zen Browser (Firefox-based); 1.21.16b
- FFmpeg Version: 6.1.1-3ubuntu5
- Playback Method: N/A
- Hardware Acceleration: none
- CPU Model: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
- GPU Model: none
- Plugins: none
- Reverse Proxy: Cloudflare Tunnel and Caddy (issue reproduces on both; does NOT occur without a proxy)
- Base URL: none set
- Networking: Bridge (LXC), internal LAN, exposed publicly via reverse proxy
- Jellyfin Data Storage & Filesystem: media/passport/tv shows & media/passport/movies
- Media Storage & Filesystem: External HDD, NTFS, mounted and bind-mounted into the container
- External Integrations: none
```

### Jellyfin logs

```shell
Logs as attachment below in Additional information. Towards the bottom where it is saying
'[2026-09-11 17:21:58.053 +00:00] [INF] [29] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.86.200" request' is where I was attempting to load the dashboard from the proxied domain
```

### FFmpeg logs

```shell

```

### Client / Browser logs

he@https://jellyfin.example.com/web/6496.59e71d86fcea8244ef07.chunk.js:1:8319
hu@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?a8c655c89450b15f6ed9:2:60311
xi@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?a8c655c89450b15f6ed9:2:119252
bs@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?a8c655c89450b15f6ed9:2:108506
vs@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?a8c655c89450b15f6ed9:2:108434
gs@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?a8c655c89450b15f6ed9:2:108295
as@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?a8c655c89450b15f6ed9:2:105130
ls@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?a8c655c89450b15f6ed9:2:103686
S@https://jellyfin.example.com/web/1133.bundle.js?a8c655c89450b15f6ed9:2:48298
C@https://jellyfin.example.com/web/1133.bundle.js?a8c655c89450b15f6ed9:2:48829
@https://jellyfin.example.com/web/node_modules.core-js.bundle.js?a8c655c89450b15f6ed9:1:73377
k@https://jellyfin.example.com/web/node_modules.core-js.bundle.js?a8c655c89450b15f6ed9:1:73145
P@https://jellyfin.example.com/web/node_modules.core-js.bundle.js?a8c655c89450b15f6ed9:1:73205

### Additional information

Confirmed reproducible across two independent reverse proxy implementations (Cloudflare Tunnel and Caddy), which rules out a proxy-specific bug and points at something general in how the web client behaves when served through any proxy vs. direct IP; a plausible candidate is a header or protocol difference (HTTPS termination at the proxy vs. plain HTTP to origin) that the client's base URL/network detection relies on, since 1133.bundle.js and the dashboard-related React chunks appear to be where a .map() call is being run against a non-array value.

(Note: I had AI help me write this report because I'm a front end developer, I don't do this kinda stuff often, and this is wayyy over my head anyways. Happy to answer any questions) 

[jellyfin-server-9-11.log](https://github.com/user-attachments/files/32125421/jellyfin-server-9-11.log)

**Comment by theguymadmax** [comment]
Have you tried clearing your browser cache? https://github.com/jellyfin/jellyfin-web/issues/8190

**Comment by wlygon7** [comment]
@theguymadmax yes. I tried that and still got it. So I tried another browser (Chrome), cleared the cookies and cache and everything still got that issue.

**Comment by theguymadmax** [comment]
What plugins are you using (listed none, but just double-checking), and please share your reverse proxy config.

**Comment by wlygon7** [comment]
@theguymadmax I don't have any, haven't gotten to mess with that yet. And reverse proxy config is through Cloudflared Tunnel Zero Dashboard. I have my https://jelly.lygonms.com (Not the actual sub domain since I don't want randos on my Jellyfin) set to the CT that runs Jellyfin's IP (192.168.86.230:8096 with http)

If you want my Caddy config I'd be happy to send it over

**Comment by theguymadmax** [comment]
Yes, and of course, put in a dummy address for the actual domain.

**Comment by wlygon7** [comment]
Sure! Here's the relevant Caddy block (domain swapped for a dummy internal one):
```
jelly.example.internal {
        reverse_proxy 192.168.86.230:8096
}
```

That domain alongside the .lygonms one (Under Cloudflare Tunnel) would give the r.map is not a function error, but the raw IP would load perfectly fine. Any idea why this is?

**Comment by kille72-dev** [comment]
I'm seeing the same issue with version 12.0: the menu is missing from the Jellyfin homepage, and I can't access the Dashboard. I'm using Jellyfin in a Docker container with Nginx Proxy Manager. The workaround is to enter the URL for the dashboard: /web/#/dashboard.

**Comment by Sylonin** [comment]
I get the same, weirdly it was working fine on 12.0 until today. removing all plugins doesn't help

**Comment by fmarcac** [comment]
Reproduced in jellyfin/jellyfin-web#8190, which should be reopened imo, if anyone can confirm they are serving static files through their reverse proxy config. This issue itself is a dupe of the linked one and in the wrong repo.

**Comment by marissa999** [comment]
I too am getting that error. In the logs I can also see something interesting:
```
Sep 14 01:23:22 mediaserver jellyfin[2006]: [01:23:22] [INF] Attempting to send 1 notifications to admins
Sep 14 01:23:22 mediaserver jellyfin[2006]: [01:23:22] [INF] No admins found
```
Obviously there should be several admins on my server

**Comment by felix-hedenstrom** [comment]
Same crash here — reproducing on lscr.io/linuxserver/jellyfin:12.0ubu2604-ls48, exact same chunk hash as this report: `6496.59e71d86fcea8244ef07.chunk.js`.

Can confirm this is not a static-file-serving issue on the proxy side. Our Caddy vhost is a bare passthrough with no file-serving directives at all:

jellyfin.example.com {
      reverse_proxy 127.0.0.1:8096
}

Fetched the crashing chunk both through the public proxied domain and directly off disk in the container — identical sha256 in both cases, served with `server: Kestrel` / `via: 1.1 Caddy` headers, so Caddy is just forwarding everything untouched and Jellyfin itself is serving the (correct, matching) static files. Rules out a stale/cached/mismatched asset as the cause on our end.

**Comment by fmarcac** [comment]
Thanks for eliminating that, just to confirm, neither you nor anyone else in this issue has set a base url (previously or currently) in `dashboard -> networking -> base url`? And if yes, what is it? (censor the domain if needed) If its empty that would eliminate one other path I'm chasing down, for which I can repro a crash but not determine how the baseurl gets set to a bad value, ignoring misconfigs

Also can anyone do this: open devtools → Application → IndexedDB → keyval-store → keyval → delete the `jellyfin-query-cache` entry then reload without changing anything else, then check if the issue immediately goes away and doesn't come back? If it comes back it means something in your current setup or current release version is still poisoning the cache, otherwise it could've been a transient error. Cloudflare serving a cached page during an origin outage is one way that could happen, but you'd need cloudflare in front of the proxy.

And for thoroughness' sake, it would help if someone posted more info about the failing request itself in devtools -> network -> `GET /web/ConfigurationPages?enableInMainMenu=true`, also tick preserve log first before navigating to dashboard then share
- Exact request url
- Status code
- If theres any request with status 302 above it
- Headers: content-type, content-length, cache-control, age, server, via, and cf-cache-status if you put cloudflare in front of the proxy
- The first few lines in the response tab

Again, censor sensitive info.

Btw @wlygon7, from the log, at 17:20 you changed some settings, do you remember what that was and was it working fine prior to that? The crash happened a minute later and I'm assuming it was working fine prior to that by the fact you could save settings. It's something that happened in that timeframe (between 17:20:47 and 17:21:58 to be exact) causing the crash.

**Comment by felix-hedenstrom** [comment]
I cannot access the dashboard gui so I looked into `config/network.xml` and it says 

```
<?xml version="1.0" encoding="utf-8"?>
<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <BaseUrl />
```
EDIT: now that I can visit the dashboard I also checked it visually - no base url

**Comment by felix-hedenstrom** [comment]
I can confirm that deleting `jellyfin-query-cache` and reloading fixes it for me. I'll get back to you if the fix doesn't work long term.

One interesting thing I noticed, cannot reproduce this for sure, but when the error was happening I looked for `ConfigurationPages` in the network tab and found no requests towards it. I looked at this three times to be sure.

Its working now so I can't reproduce it a fourth time.

**Comment by felix-hedenstrom** [comment]
Did not take too long. Now I have a different error on the dashboard. This is visible on the page
```
TypeError

j.find is not a function

73422/on/S<@https://jellyfin.example.com/web/index.7675b6544b20e6ce0ef7.chunk.js:1:31436
useMemo@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:66609
14403/t.useMemo@https://jellyfin.example.com/web/1133.bundle.js?92243be6e1b950a9de11:2:46448
on@https://jellyfin.example.com/web/index.7675b6544b20e6ce0ef7.chunk.js:1:31399
hu@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:60311
xi@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:119252
bs@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:108506
vs@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:108434
gs@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:108295
as@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:105130
is@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:105512
Bl@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:46687
76067/rs/<@https://jellyfin.example.com/web/node_modules.react-dom.bundle.js?92243be6e1b950a9de11:2:103087
```

with one of the stand out errors in the console being
`TypeError: 'get persisted' called on an object that does not implement interface PageTransitionEvent.`

**Comment by felix-hedenstrom** [comment]
Note: after the cache was cleared and I got the `j.find` error I saw a request to ConfigurationPages. 

GET /web/ConfigurationPages?enableInMainMenu=true

- Anonymized request URL: https://jellyfin.example.com/web/ConfigurationPages?enableInMainMenu=true
- Status code: 200
- Any 302 above it in the chain: none — no redirects at all for this request
- Headers:
  - content-type: application/json; charset=utf-8
  - content-length: not present (response uses content-encoding: br, chunked transfer)
  - cache-control: not present
  - age: not present
  - server: Kestrel
  - via: 1.1 Caddy
  - cf-cache-status: n/a — no Cloudflare in front of our proxy
- Response body:
[]

**Comment by fmarcac** [comment]
@felix-hedenstrom That helped narrow it down. So it's not anything to do with BaseUrl with your evidence or websockets, which I couldn't find a code path for. Can I bother you with one more thing? Run this in console when you hit the error and before clearing the cache. It only reads, formats and prints values so you don't have to go through IndexedDB manually, doesn't write anything to it and exposes no sensitive data. Then paste just the script output here (not the whole console). Btw I think you're on firefox so you'll have to run `allow pasting` in console first.

```javascript
(async () => {
  const K = ['ConfigurationPages', 'Packages', 'Plugins', 'Repositories', 'Tasks'];
  const db = await new Promise(r => { const q = indexedDB.open('keyval-store'); q.onsuccess = () => r(q.result); });
  const v = await new Promise(r => { const t = db.transaction('keyval').objectStore('keyval').get('jellyfin-query-cache'); t.onsuccess = () => r(t.result); });
  const qs = v.clientState.queries;
  const cap = function (s) {
    if (s == null) return String(s);
    return s.length > 400 ? s.slice(0, 200) + ' ...[' + s.length + ' chars total]... ' + s.slice(-200) : s;
  };
  const out = qs
    .filter(function (q) {
      return typeof q.state.data === 'string'
        || (K.indexOf(q.queryKey[0]) !== -1 && !Array.isArray(q.state.data));
    })
    .map(function (q) {
      const d = q.state.data;
      return {
        key: q.queryKey,
        status: q.state.status,
        type: d === null ? 'null' : typeof d,
        updated: new Date(q.state.dataUpdatedAt).toISOString(),
        value: cap(typeof d === 'string' ? d : JSON.stringify(d))
      };
    });
  console.log('checked ' + qs.length + ' cached queries, ' + out.length + ' suspect');
  console.log(JSON.stringify(out, null, 2));
})()
```

**Comment by felix-hedenstrom** [comment]
> [@felix-hedenstrom](https://github.com/felix-hedenstrom) That helped narrow it down. So it's not anything to do with BaseUrl with your evidence or websockets, which I couldn't find a code path for. Can I bother you with one more thing? Run this in console when you hit the error and before clearing the cache. It only reads, formats and prints values so you don't have to go through IndexedDB manually, doesn't write anything to it and exposes no sensitive data. Then paste just the script output here (not the whole console). Btw I think you're on firefox so you'll have to run `allow pasting` in console first.
> 
> (async () => {
>   const K = ['ConfigurationPages', 'Packages', 'Plugins', 'Repositories', 'Tasks'];
>   const db = await new Promise(r => { const q = indexedDB.open('keyval-store'); q.onsuccess = () => r(q.result); });
>   const v = await new Promise(r => { const t = db.transaction('keyval').objectStore('keyval').get('jellyfin-query-cache'); t.onsuccess = () => r(t.result); });
>   const qs = v.clientState.queries;
>   const cap = function (s) {
>     if (s == null) return String(s);
>     return s.length > 400 ? s.slice(0, 200) + ' ...[' + s.length + ' chars total]... ' + s.slice(-200) : s;
>   };
>   const out = qs
>     .filter(function (q) {
>       return typeof q.state.data === 'string'
>         || (K.indexOf(q.queryKey[0]) !== -1 && !Array.isArray(q.state.data));
>     })
>     .map(function (q) {
>       const d = q.state.data;
>       return {
>         key: q.queryKey,
>         status: q.state.status,
>         type: d === null ? 'null' : typeof d,
>         updated: new Date(q.state.dataUpdatedAt).toISOString(),
>         value: cap(typeof d === 'string' ? d : JSON.stringify(d))
>       };
>     });
>   console.log('checked ' + qs.length + ' cached queries, ' + out.length + ' suspect');
>   console.log(JSON.stringify(out, null, 2));
> })()

```json
[
  {
    "key": [
      "ConfigurationPages",
      true
    ],
    "status": "success",
    "type": "string",
    "updated": "2026-09-14T07:27:59.051Z",
    "value": ""
  },
  {
    "key": [
      "Tasks"
    ],
    "status": "success",
    "type": "string",
    "updated": "2026-09-14T07:27:59.051Z",
    "value": ""
  },
  {
    "key": [
      "ActivityLogEntries",
      {
        "startIndex": 0,
        "limit": 7,
        "minDate": "2026-09-13T06:51:48.241Z",
        "hasUserId": true
      }
    ],
    "status": "success",
    "type": "string",
    "updated": "2026-09-14T07:27:59.051Z",
    "value": ""
  },
  {
    "key": [
      "ActivityLogEntries",
      {
        "startIndex": 0,
        "limit": 4,
        "minDate": "2026-09-07T06:51:48.241Z",
        "hasUserId": false
      }
    ],
    "status": "success",
    "type": "string",
    "updated": "2026-09-14T07:27:59.051Z",
    "value": ""
  }
]
```

**Comment by felix-hedenstrom** [comment]
Might be relevant, maybe not: 

I started using jellyfin with a fresh install of `lscr.io/linuxserver/jellyfin:10.11.7` on the 12th of september which I almost immediately upgraded to `12.0`.

So my server had very little previous config and I have not had the time to customize it that much.

**Comment by wlygon7** [comment]
@fmarcac I think I remember, it was one of 2 things:
1. I added an account for my little sister to use (excluding the ability to watch TV shows) 
Or it was
2. I changed the libraries' file path. I'm using an external HDD to store the movies and shows, but the process of loading stuff onto the HDD takes forever, so I connected it to Jellyfin to rsync everything a local path and pointed the libraries there so I can sit back and watch something (Like House MD) while waiting on other shows/movies to get on the HDD.

Regardless, this crash was happening right from the get-go. I was having the r.map is not a function error since I first booted Jellyfin up, so neither of these changes would have effected it since I've had this error since the moment I first started the Jellyfin container.

**Comment by jordanhillis** [comment]
I’m seeing this same issue on **Jellyfin 12.1.0**. I did some digging into it tonight and was able to narrow down exactly where the `r.map is not a function` error is coming from.

For me, the Dashboard works perfectly if I access Jellyfin directly using the server IP and port. If I access the exact same server/account through my public domain behind the reverse proxy, going to Administration → Dashboard crashes with:

```text
TypeError: r.map is not a function
    he .../web/6496.59e71d86fcea8244ef07.chunk.js:1
```

I also get this right before it:

```text
TypeError: j.find is not a function
    S .../web/index.0c00a1c0be9352515e94.chunk.js:1
```

I pulled apart `6496.59e71d86fcea8244ef07.chunk.js` to see what `r` actually is.

The failing function is `PluginDrawerSection`, and the relevant code is basically:

```js
var e = useConfigurationPages({ enableInMainMenu: true }),
    r = e.data,
    n = e.error;

...

r?.map(...)
```

Following that query further, `r` is the `response.data` returned from:

```js
getConfigurationPages(...)
```

So it looks like the Dashboard expects the ConfigurationPages response to always be an array, but when this happens `r` is something else. Since it isn't null/undefined, the existing `r?.map()` check doesn't help and it ends up trying to call `.map()` on a non-array.

A simple defensive fix would be something along the lines of:

```js
const configurationPages = Array.isArray(data) ? data : [];
```

and then:

```js
configurationPages.map(...)
```

instead of directly doing:

```js
data?.map(...)
```

That should at least stop `PluginDrawerSection` from taking down the entire Dashboard when the response isn't an array.

I don't think that explains the actual root cause though. The weird part is that **the same server works fine over IP:port and fails through the public domain/reverse proxy**.

So I think the real thing to figure out is why `getConfigurationPages()` is ending up with a different response/data type when Jellyfin is accessed through the reverse proxy.

**Comment by koboshchan** [comment]
for nginx, under `location / {`, adding 

```
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
```

and reloading without cache (shift + reload)

seems to fix for me.

**Comment by jordanhillis** [comment]
Yep, adding this to my Nginx config fixed it:

```nginx
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
```

From what I can tell, Nginx wasn't properly passing the HTTP/1.1 upgrade/WebSocket headers through to Jellyfin. The regular web UI would still load, which made it look like the proxy was working fine, but parts of the admin dashboard communication were breaking behind the scenes.

After adding those headers and reloading Nginx, the dashboard immediately started working normally through the public domain. Since direct IP:port access was already working, this ended up being a reverse proxy/WebSocket issue rather than Jellyfin itself.
